name: Node.js Express web app protected with App ID
version: 0.0.1
description: Node.js Express web app protected with App ID
license: Apache-2.0
language: nodejs
maintainers:
  - name: Anton Aleksandrov
    email: antona@us.ibm.com
    github-id: aal80
default-template: webapp
